reqour:
  git:
    git-providers:
      gitlab:
        enabled: true
        hostname: localhost
        url: http://${reqour.git.git-providers.gitlab.hostname}:${quarkus.wiremock.devservices.port}
        username: test-user
        workspace: test-workspace
        workspace-id: 1
        token: I don't even need to be real
        read-only-template: http://${reqour.git.git-providers.gitlab.hostname}/${reqour.git.git-providers.gitlab.workspace}/%s.git
        protected-tags-pattern: '*'
        protected-tags-accepted-patterns:
      github:
        enabled: false
        hostname: localhost
        url: http://${reqour.git.git-providers.github.hostname}:${quarkus.wiremock.devservices.port}
        username: test-user
        internal-organization: test-organization
        token: I don't even need to be real
        read-only-template: http://${reqour.git.git-providers.github.hostname}/${reqour.git.git-providers.github.internal-organization}/%s.git
        protected-tags-pattern: '*'
        protected-tags-accepted-patterns:
      fault-tolerance:
        retry:
          max-retries: 2
          initial-delay: 1
          initial-delay-unit: seconds
    acceptable-schemes:
      - https
      - http
      - git
      - git+ssh
      - ssh
    private-github-user: test-bot
    user:
      email: test-user@example.com
      name: ReqourTest
  log:
    final-log:
      bifrost-uploader:
        base-url: http://localhost:${quarkus.wiremock.devservices.port}
  adjuster:
    alignment:
      validate: true
      request: >
        {
          "ref": "main",
          "callback": {
            "method": "POST",
            "uri": "http://localhost:${quarkus.wiremock.devservices.port}/callback"
          },
          "sync": true,
          "originRepoUrl": "git@gitlab.com:repo/project.git",
          "buildConfigParameters": {
          },
          "tempBuild": false,
          "taskId": "task123",
          "buildType": "MVN",
          "pncDefaultAlignmentParameters": "-DdependencySource=REST -DrepoRemovalBackup=repositories-backup.xml -DversionSuffixStrip= -DreportNonAligned=true",
          "brewPullActive": false,
          "internalUrl": {
            "readwriteUrl": "git@gitlab.com:test-workspace/repo/project.git",
            "readonlyUrl": "https://gitlab.com/test-workspace/repo/project.git"
          },
          "heartbeatConfig": {
            "request": {
              "method": "POST",
              "uri": "http://localhost:${quarkus.wiremock.devservices.port}${test.heartbeat.path}"
            },
            "delay": 1,
            "delayTimeUnit": "SECONDS"
          }
        }
      mvn:
        cli-jar-path: '${test.location.providers.mvn}/pom-manipulation-cli.jar'
        default-settings-file-path: '${test.location.providers.mvn}/settings.xml'
        temporary-settings-file-path: '${test.location.providers.mvn}/temporary-settings.xml'
        alignment-parameters:
          - '-DconfigAlignmentParam=foo'
          - '-DrestURL=https://da.com/rest/v-1'
          - '-DversionIncrementalSuffix=redhat'
          - '-Doverride=config'
      gradle:
        gradle-analyzer-plugin-init-file-path: '${test.location.providers.gradle}/analyzer-init.gradle'
        cli-jar-path: '${test.location.providers.gradle}/gme-cli.jar'
        default-gradle-path: '${test.location.providers.gradle}/gradle-5.5.1'
        alignment-parameters:
          - '-Doverride=config'
      scala:
        sbt-path: '${test.location.providers.sbt}/sbt'
        alignment-parameters:
          - '-Doverride=config'
      npm:
        cli-jar-path: '${test.location.providers.npm}/project-manipulator-cli.jar'
        alignment-parameters:
          - '-Doverride=config'
          - '-DversionIncrementalSuffix=config'
    maven-executable: './mvnw'
    mdc: '{}'
  rest:
    app-environment: test
    reqour-secret-key: test-secret
    indy-url: https://test.indy.com
    sasl-jaas-conf: sasl-jaas-config
    job-definition-file-path: 'src/test/resources/job.yaml'

quarkus:
  log:
    console:
      json: false
    category:
      "org.jboss.pnc._userlog_":
        level: DEBUG
  oidc:
    enabled: false
  oidc-client:
    enabled: false
  otel:
    enabled: false

test:
  location:
    test-resources: 'src/test/resources'
    requests:
      dir: '${test.location.test-resources}/requests'
    providers:
      dir: '${test.location.test-resources}/providers'
      mvn: '${test.location.providers.dir}/mvn'
      gradle: '${test.location.providers.dir}/gradle'
      sbt: '${test.location.providers.dir}/sbt'
      npm: '${test.location.providers.dir}/npm'
  heartbeat:
    path: /heartbeat
wiremock:
  base-url: http://localhost:${quarkus.wiremock.devservices.port}
