quarkus:
  oidc:
    enabled: false
  oidc-client:
    enabled: false
  otel:
    enabled: false

reqour-rest:
  app-environment: devel
  reqour-secret-key: devel-secret-dummy-key
  indy-url: https://dev-indy.example.com
